### ISSUE TITLE
GenServer terminating with noproc

### ISSUE THREAD

**Issue by talklittle** [codedge-llc/kadabra#24]
Kadabra 0.3.5, Pigeon 1.1.2

This error seems benign, since my application continues to run after the GenServer crashes, but it is showing up in error logs nonetheless.

```
06:51:30.997 [error] Got GOAWAY, NO_ERROR, Last Stream: 2147483647, Rest: max_age
06:51:30.999 [error] GenServer {Registry.Kadabra, {#PID<0.3511.1>, Kadabra.Connection}} terminating
** (stop) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen.erl:279: :gen.do_for_proc/2
    (kadabra) lib/connection.ex:151: anonymous fn/3 in Kadabra.Connection.close/1
    (elixir) lib/enum.ex:1839: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/enum.ex:3176: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1838: Enum.reduce/3
    (kadabra) lib/connection.ex:150: Kadabra.Connection.close/1
    (kadabra) lib/connection.ex:197: Kadabra.Connection.recv/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
Last message: {:"$gen_cast", {:recv, %Kadabra.Frame.Goaway{debug_data: "max_age", error_code: 0, last_stream_id: 2147483647}}}

=CRASH REPORT==== 5-Dec-2017::06:51:30 ===
  crasher:
    initial call: Elixir.Kadabra.Connection:init/1
    pid: <0.3516.1>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 279)
      in call from 'Elixir.Kadabra.Connection':'-close/1-fun-0-'/3 (lib/connection.ex, line 151)
      in call from 'Elixir.Enum':'-reduce/3-fun-0-'/3 (lib/enum.ex, line 1839)
      in call from 'Elixir.Enumerable.List':reduce/3 (lib/enum.ex, line 3176)
      in call from 'Elixir.Enum':reduce/3 (lib/enum.ex, line 1838)
      in call from 'Elixir.Kadabra.Connection':close/1 (lib/connection.ex, line 150)
      in call from 'Elixir.Kadabra.Connection':recv/2 (lib/connection.ex, line 197)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
    ancestors: [<0.3513.1>,<0.3511.1>,<0.3510.1>,pigeon,<0.1686.0>]
    message_queue_len: 1
    messages: [{finished,#{'__struct__' => 'Elixir.Kadabra.Stream.Response',
                              body =>
                                  <<"{\"multicast_id\":snip,\"success\":24,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"snip\"},...]}">>,
                              headers =>
                                  [{<<":status">>,<<"200">>},
                                   {<<"content-type">>,
                                    <<"application/json; charset=UTF-8">>},
                                   {<<"date">>,
                                    <<"Tue, 05 Dec 2017 06:51:31 GMT">>},
                                   {<<"expires">>,
                                    <<"Tue, 05 Dec 2017 06:51:31 GMT">>},
                                   {<<"cache-control">>,
                                    <<"private, max-age=0">>},
                                   {<<"x-content-type-options">>,
                                    <<"nosniff">>},
                                   {<<"x-frame-options">>,<<"SAMEORIGIN">>},
                                   {<<"x-xss-protection">>,
                                    <<"1; mode=block">>},
                                   {<<"server">>,<<"GSE">>},
                                   {<<"alt-svc">>,
                                    <<"hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\"">>},
                                   {<<"accept-ranges">>,<<"none">>},
                                   {<<"vary">>,<<"Accept-Encoding">>}],
                              id => 5547,status => 200}}]
    links: [<0.1654.0>,<0.3513.1>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1351842
  neighbours:

=SUPERVISOR REPORT==== 5-Dec-2017::06:51:31 ===
     Supervisor: {via,'Elixir.Registry',
                     {'Elixir.Registry.Kadabra',
                         {#Ref<0.2126317446.661389313.65541>,
                          'Elixir.Kadabra.ConnectionSupervisor'}}}
     Context:    child_terminated
     Reason:     noproc
     Offender:   [{pid,<0.3516.1>},
                  {id,connection},
                  {mfargs,
                      {'Elixir.Kadabra.Connection',start_link,
                          ["fcm.googleapis.com",<0.3510.1>,<0.3511.1>,
                           #Ref<0.2126317446.661389313.65541>,
                           [{scheme,https},
                            {ssl,
                                [{active,once},
                                 {packet,raw},
                                 {reuseaddr,true},
                                 {alpn_advertised_protocols,[<<"h2">>]},
                                 binary]},
                            {port,443},
                            {reconnect,false}]]}},
                  {restart_type,transient},
                  {shutdown,5000},
                  {child_type,worker}]
```

**Comment by hpopp** [comment]
It's weird because `Kadabra.Connection` should never receive a GOAWAY max stream when used with the latest pigeon. What Elixir/OTP are you running?

**Comment by talklittle** [comment]
I haven't seen the error again, so it's probably something I did wrong. Sorry, closing issue.

(Elixir 1.5.2, OTP 20)

**Comment by talklittle** [comment]
The error has shown up in logs a couple more times, after I've reset the server to make sure it's not running old processes.

**Comment by hpopp** [comment]
Published Pigeon v1.1.3 which may have helped alleviate the problem. The worker now explicitly queues demand and ensures a connection is live before pushing, instead of letting GenStage handle it internally. I think there was some sort of race condition going on (and maybe still).

What kind of load are you pushing through FCM? It seems like you're exhausting stream identifiers pretty often, which implies 1 billion pushes each time.

**Comment by talklittle** [comment]
> What kind of load are you pushing through FCM? It seems like you're exhausting stream identifiers pretty often, which implies 1 billion pushes each time.

About 5 per second, each consisting of maybe 50 devices on average; but the number of devices probably doesn't matter. Yeah, the numbers seem off because at that rate, by my calculation it'd take years to go through a billion. Unless there's something else burning through stream IDs too.

**Comment by hpopp** [comment]
Finally saw this crop up in one of my projects. It's definitely a race condition with GOAWAY frames. Will have a fix up shortly.
